### ISSUE TITLE
sudo dotnet ef database update

### ISSUE THREAD

**Issue by xiote** [dotnet/EntityFramework.Docs.ko-kr#9]
dotnet ef database update
-&gt;
sudo dotnet ef database update
on macos

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [마이그레이션 - EF Core](https://docs.microsoft.com/ko-kr/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs.ko-kr/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by srvbpigh** [comment]
Hello, @xiote
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by xiote** [comment]
i use sqlite db

**Comment by V-vafune** [comment]
Hello, @xiote, 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

 Kind regards, 

Microsoft DOCS International Team

**Comment by bricelam** [comment]
You shouldn't need to use sudo. Check your file permissions.

**Comment by xiote** [comment]
thank you
